# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Cpp function for Exercise 9.4
#' @description Cpp function for Exercise 9.4
#' @param sigma the variance of the normality distribution
#' @param x_0 the original value
#' @param N the size
#' @return the sample x \code{n}
#' @export
rwC <- function(sigma, x_0, N) {
    .Call('_SC19037_rwC', PACKAGE = 'SC19037', sigma, x_0, N)
}

